name: Tests

on: [push, pull_request]

jobs:
  python-import:
    name: Python import
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ github.token }}
      - name: Update packages
        run: sudo apt-get update -yq
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get install -yq libuv1-dev python3-dev
          pip install pytest requests Flask
      - name: Install FastWSGI Extension
        run: python setup.py install
      - name: Test FastWSGI Python module import
        run: python -c "import fastwsgi"
